spring:
  profiles:
    active: default
  jackson:
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false

server:
  port: ${port:4000}

---

spring:
  profiles: default
  datasource:
    url: ${JDBC_DATABASE_URL}
    driver-class-name: org.postgresql.Driver
    username: ${JDBC_DATABASE_USERNAME}
    password: ${JDBC_DATABASE_PASSWORD}

logging:
  file: ionic-chat-client-server.log
  level:
    com:
      alimmit: DEBUG

#auth:
#  server:
#    url: ${AUTHORIZATION_SERVER_URL}
#    clientId: ${AUTHORIZATION_CLIENT_ID}
#    clientSecret: ${AUTHORIZATION_CLIENT_SECRET}
#    tokenSigningKey: abc123

auth:
  client:
    clientId: ${AUTHORIZATION_CLIENT_ID}
    clientSecret: ${AUTHORIZATION_CLIENT_SECRET}
    accessTokenUri: ${AUTHORIZATION_SERVER_ACCESS_TOKEN_URL}
    checkTokenUri: ${AUTHORIZATION_SERVER_CHECK_TOKEN_URL}
    signUpUri: ${AUTHORIZATION_SERVER_SIGN_UP_URL}
    tokenSigningKey: abc123
  resource:
    userInfoUri: ${AUTHORIZATION_SERVER_USER_INFO_URL}
